FROM python:3.11-slim

WORKDIR /app

# Installation des dépendances système pour PostgreSQL
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    postgresql-client\
    curl\
    && rm -rf /var/lib/apt/lists/* 

# Copie des fichiers de configuration
COPY requirements.txt .
COPY entrypoint.sh .
COPY initialize_db.py .
COPY streamlit_app.py .

# Installation des dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Rendre le script exécutable
RUN chmod +x entrypoint.sh

EXPOSE 8501 8888

ENTRYPOINT ["./entrypoint.sh"]